build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.17"
  amd64: "ghcr.io/home-assistant/amd64-base:3.17"
  armhf: "ghcr.io/home-assistant/armhf-base:3.17"
  armv7: "ghcr.io/home-assistant/armv7-base:3.17"
  i386: "ghcr.io/home-assistant/i386-base:3.17"
labels:
  org.opencontainers.image.title: "SNMPD"
  org.opencontainers.image.description: "Monitor your HA installation via snmp"
  org.opencontainers.image.source: "https://github.com/mib1185/ha-addon-snmpd"
  org.opencontainers.image.licenses: "Apache License 2.0"
