name: Build add-on

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  build:
    runs-on: ${{ contains(fromJson('["armhf", "armv7", "aarch64"]'), matrix.arch) && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    name: Build ${{ matrix.arch }} snmpd add-on
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./snmpd"

      - name: Set build arguments
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              echo "TEST_FLAG=--test" >> $GITHUB_ENV;
          fi
          if [[ "${{ github.event_name }}" == "push" ]] && [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "VERSION_FLAG=--version dev --no-latest" >> $GITHUB_ENV;
          fi

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build snmpd add-on
        uses: home-assistant/builder@2025.02.0
        with:
          image: ${{ contains(fromJson('["armhf", "armv7", "aarch64"]'), matrix.arch) && 'aarch64' || 'amd64' }}
          args: |
            ${{ env.TEST_FLAG }} \
            ${{ env.VERSION_FLAG }} \
            --${{ matrix.arch }} \
            --target /data/snmpd \
            --addon
